# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/profiler/protobuf/trace_events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4tensorflow/core/profiler/protobuf/trace_events.proto\x12\x13tensorflow.profiler\"\xc5\x01\n\x05Trace\x12\x38\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\'.tensorflow.profiler.Trace.DevicesEntry\x12\x35\n\x0ctrace_events\x18\x04 \x03(\x0b\x32\x1f.tensorflow.profiler.TraceEvent\x1aK\n\x0c\x44\x65vicesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.tensorflow.profiler.Device:\x02\x38\x01\"\xb9\x01\n\x06\x44\x65vice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\r\x12=\n\tresources\x18\x03 \x03(\x0b\x32*.tensorflow.profiler.Device.ResourcesEntry\x1aO\n\x0eResourcesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.tensorflow.profiler.Resource:\x02\x38\x01\"A\n\x08Resource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bresource_id\x18\x02 \x01(\r\x12\x12\n\nsort_index\x18\x03 \x01(\r\"\xd3\x01\n\nTraceEvent\x12\x11\n\tdevice_id\x18\x01 \x01(\r\x12\x13\n\x0bresource_id\x18\x02 \x01(\r\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0ctimestamp_ps\x18\t \x01(\x04\x12\x13\n\x0b\x64uration_ps\x18\n \x01(\x04\x12\x37\n\x04\x61rgs\x18\x0b \x03(\x0b\x32).tensorflow.profiler.TraceEvent.ArgsEntry\x1a+\n\tArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42|\n\x18org.tensorflow.frameworkB\x11TraceEventsProtosP\x01ZHgithub.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto\xf8\x01\x01\x62\x06proto3')



_TRACE = DESCRIPTOR.message_types_by_name['Trace']
_TRACE_DEVICESENTRY = _TRACE.nested_types_by_name['DevicesEntry']
_DEVICE = DESCRIPTOR.message_types_by_name['Device']
_DEVICE_RESOURCESENTRY = _DEVICE.nested_types_by_name['ResourcesEntry']
_RESOURCE = DESCRIPTOR.message_types_by_name['Resource']
_TRACEEVENT = DESCRIPTOR.message_types_by_name['TraceEvent']
_TRACEEVENT_ARGSENTRY = _TRACEEVENT.nested_types_by_name['ArgsEntry']
Trace = _reflection.GeneratedProtocolMessageType('Trace', (_message.Message,), {

  'DevicesEntry' : _reflection.GeneratedProtocolMessageType('DevicesEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRACE_DEVICESENTRY,
    '__module__' : 'tensorflow.core.profiler.protobuf.trace_events_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.profiler.Trace.DevicesEntry)
    })
  ,
  'DESCRIPTOR' : _TRACE,
  '__module__' : 'tensorflow.core.profiler.protobuf.trace_events_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.profiler.Trace)
  })
_sym_db.RegisterMessage(Trace)
_sym_db.RegisterMessage(Trace.DevicesEntry)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {

  'ResourcesEntry' : _reflection.GeneratedProtocolMessageType('ResourcesEntry', (_message.Message,), {
    'DESCRIPTOR' : _DEVICE_RESOURCESENTRY,
    '__module__' : 'tensorflow.core.profiler.protobuf.trace_events_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.profiler.Device.ResourcesEntry)
    })
  ,
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'tensorflow.core.profiler.protobuf.trace_events_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.profiler.Device)
  })
_sym_db.RegisterMessage(Device)
_sym_db.RegisterMessage(Device.ResourcesEntry)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCE,
  '__module__' : 'tensorflow.core.profiler.protobuf.trace_events_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.profiler.Resource)
  })
_sym_db.RegisterMessage(Resource)

TraceEvent = _reflection.GeneratedProtocolMessageType('TraceEvent', (_message.Message,), {

  'ArgsEntry' : _reflection.GeneratedProtocolMessageType('ArgsEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRACEEVENT_ARGSENTRY,
    '__module__' : 'tensorflow.core.profiler.protobuf.trace_events_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.profiler.TraceEvent.ArgsEntry)
    })
  ,
  'DESCRIPTOR' : _TRACEEVENT,
  '__module__' : 'tensorflow.core.profiler.protobuf.trace_events_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.profiler.TraceEvent)
  })
_sym_db.RegisterMessage(TraceEvent)
_sym_db.RegisterMessage(TraceEvent.ArgsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.tensorflow.frameworkB\021TraceEventsProtosP\001ZHgithub.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto\370\001\001'
  _TRACE_DEVICESENTRY._options = None
  _TRACE_DEVICESENTRY._serialized_options = b'8\001'
  _DEVICE_RESOURCESENTRY._options = None
  _DEVICE_RESOURCESENTRY._serialized_options = b'8\001'
  _TRACEEVENT_ARGSENTRY._options = None
  _TRACEEVENT_ARGSENTRY._serialized_options = b'8\001'
  _TRACE._serialized_start=78
  _TRACE._serialized_end=275
  _TRACE_DEVICESENTRY._serialized_start=200
  _TRACE_DEVICESENTRY._serialized_end=275
  _DEVICE._serialized_start=278
  _DEVICE._serialized_end=463
  _DEVICE_RESOURCESENTRY._serialized_start=384
  _DEVICE_RESOURCESENTRY._serialized_end=463
  _RESOURCE._serialized_start=465
  _RESOURCE._serialized_end=530
  _TRACEEVENT._serialized_start=533
  _TRACEEVENT._serialized_end=744
  _TRACEEVENT_ARGSENTRY._serialized_start=701
  _TRACEEVENT_ARGSENTRY._serialized_end=744
# @@protoc_insertion_point(module_scope)
