"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.internal.extension_dict
import google.protobuf.message
import tensorflow.core.framework.types_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Color:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _ColorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Color.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RED: _Color.ValueType  # 0
    ORANGE: _Color.ValueType  # 1
    YELLOW: _Color.ValueType  # 2
    GREEN: _Color.ValueType  # 3
    BLUE: _Color.ValueType  # 4
    INDIGO: _Color.ValueType  # 5
    VIOLET: _Color.ValueType  # 6
class Color(_Color, metaclass=_ColorEnumTypeWrapper):
    pass

RED: Color.ValueType  # 0
ORANGE: Color.ValueType  # 1
YELLOW: Color.ValueType  # 2
GREEN: Color.ValueType  # 3
BLUE: Color.ValueType  # 4
INDIGO: Color.ValueType  # 5
VIOLET: Color.ValueType  # 6
global___Color = Color


class TestCase(google.protobuf.message.Message):
    """A TestCase holds a proto and assertions about how it should decode."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUES_FIELD_NUMBER: builtins.int
    SHAPES_FIELD_NUMBER: builtins.int
    SIZES_FIELD_NUMBER: builtins.int
    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TestValue]:
        """Batches of primitive values."""
        pass
    @property
    def shapes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """The batch shapes."""
        pass
    @property
    def sizes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Expected sizes for each field."""
        pass
    @property
    def fields(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___FieldSpec]:
        """Expected values for each field."""
        pass
    def __init__(self,
        *,
        values: typing.Optional[typing.Iterable[global___TestValue]] = ...,
        shapes: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sizes: typing.Optional[typing.Iterable[builtins.int]] = ...,
        fields: typing.Optional[typing.Iterable[global___FieldSpec]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fields",b"fields","shapes",b"shapes","sizes",b"sizes","values",b"values"]) -> None: ...
global___TestCase = TestCase

class FieldSpec(google.protobuf.message.Message):
    """FieldSpec describes the expected output for a single field."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: typing.Text
    dtype: tensorflow.core.framework.types_pb2.DataType.ValueType
    @property
    def value(self) -> global___TestValue: ...
    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        dtype: typing.Optional[tensorflow.core.framework.types_pb2.DataType.ValueType] = ...,
        value: typing.Optional[global___TestValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["dtype",b"dtype","name",b"name","value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["dtype",b"dtype","name",b"name","value",b"value"]) -> None: ...
global___FieldSpec = FieldSpec

class TestValue(google.protobuf.message.Message):
    """NOTE: This definition must be kept in sync with PackedTestValue."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    FLOAT_VALUE_FIELD_NUMBER: builtins.int
    INT64_VALUE_FIELD_NUMBER: builtins.int
    UINT64_VALUE_FIELD_NUMBER: builtins.int
    INT32_VALUE_FIELD_NUMBER: builtins.int
    FIXED64_VALUE_FIELD_NUMBER: builtins.int
    FIXED32_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    BYTES_VALUE_FIELD_NUMBER: builtins.int
    UINT32_VALUE_FIELD_NUMBER: builtins.int
    SFIXED32_VALUE_FIELD_NUMBER: builtins.int
    SFIXED64_VALUE_FIELD_NUMBER: builtins.int
    SINT32_VALUE_FIELD_NUMBER: builtins.int
    SINT64_VALUE_FIELD_NUMBER: builtins.int
    MESSAGE_VALUE_FIELD_NUMBER: builtins.int
    ENUM_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    FLOAT_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    INT64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    UINT64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    INT32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    FIXED64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    FIXED32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    BOOL_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    STRING_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    BYTES_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    UINT32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    SFIXED32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    SFIXED64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    SINT32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    SINT64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    ENUM_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    @property
    def double_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def float_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def int64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def uint64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def int32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def fixed64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def fixed32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def bool_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    @property
    def string_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def bytes_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def uint32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sfixed32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sfixed64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sint32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sint64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def message_value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PrimitiveValue]: ...
    @property
    def enum_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Color.ValueType]: ...
    double_value_with_default: builtins.float
    """Optional fields with explicitly-specified defaults."""

    float_value_with_default: builtins.float
    int64_value_with_default: builtins.int
    uint64_value_with_default: builtins.int
    int32_value_with_default: builtins.int
    fixed64_value_with_default: builtins.int
    fixed32_value_with_default: builtins.int
    bool_value_with_default: builtins.bool
    string_value_with_default: typing.Text
    bytes_value_with_default: builtins.bytes
    uint32_value_with_default: builtins.int
    sfixed32_value_with_default: builtins.int
    sfixed64_value_with_default: builtins.int
    sint32_value_with_default: builtins.int
    sint64_value_with_default: builtins.int
    enum_value_with_default: global___Color.ValueType
    def __init__(self,
        *,
        double_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        float_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        int64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        uint64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        int32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        fixed64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        fixed32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        bool_value: typing.Optional[typing.Iterable[builtins.bool]] = ...,
        string_value: typing.Optional[typing.Iterable[typing.Text]] = ...,
        bytes_value: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        uint32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sfixed32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sfixed64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sint32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sint64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        message_value: typing.Optional[typing.Iterable[global___PrimitiveValue]] = ...,
        enum_value: typing.Optional[typing.Iterable[global___Color.ValueType]] = ...,
        double_value_with_default: typing.Optional[builtins.float] = ...,
        float_value_with_default: typing.Optional[builtins.float] = ...,
        int64_value_with_default: typing.Optional[builtins.int] = ...,
        uint64_value_with_default: typing.Optional[builtins.int] = ...,
        int32_value_with_default: typing.Optional[builtins.int] = ...,
        fixed64_value_with_default: typing.Optional[builtins.int] = ...,
        fixed32_value_with_default: typing.Optional[builtins.int] = ...,
        bool_value_with_default: typing.Optional[builtins.bool] = ...,
        string_value_with_default: typing.Optional[typing.Text] = ...,
        bytes_value_with_default: typing.Optional[builtins.bytes] = ...,
        uint32_value_with_default: typing.Optional[builtins.int] = ...,
        sfixed32_value_with_default: typing.Optional[builtins.int] = ...,
        sfixed64_value_with_default: typing.Optional[builtins.int] = ...,
        sint32_value_with_default: typing.Optional[builtins.int] = ...,
        sint64_value_with_default: typing.Optional[builtins.int] = ...,
        enum_value_with_default: typing.Optional[global___Color.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bool_value_with_default",b"bool_value_with_default","bytes_value_with_default",b"bytes_value_with_default","double_value_with_default",b"double_value_with_default","enum_value_with_default",b"enum_value_with_default","fixed32_value_with_default",b"fixed32_value_with_default","fixed64_value_with_default",b"fixed64_value_with_default","float_value_with_default",b"float_value_with_default","int32_value_with_default",b"int32_value_with_default","int64_value_with_default",b"int64_value_with_default","sfixed32_value_with_default",b"sfixed32_value_with_default","sfixed64_value_with_default",b"sfixed64_value_with_default","sint32_value_with_default",b"sint32_value_with_default","sint64_value_with_default",b"sint64_value_with_default","string_value_with_default",b"string_value_with_default","uint32_value_with_default",b"uint32_value_with_default","uint64_value_with_default",b"uint64_value_with_default"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool_value",b"bool_value","bool_value_with_default",b"bool_value_with_default","bytes_value",b"bytes_value","bytes_value_with_default",b"bytes_value_with_default","double_value",b"double_value","double_value_with_default",b"double_value_with_default","enum_value",b"enum_value","enum_value_with_default",b"enum_value_with_default","fixed32_value",b"fixed32_value","fixed32_value_with_default",b"fixed32_value_with_default","fixed64_value",b"fixed64_value","fixed64_value_with_default",b"fixed64_value_with_default","float_value",b"float_value","float_value_with_default",b"float_value_with_default","int32_value",b"int32_value","int32_value_with_default",b"int32_value_with_default","int64_value",b"int64_value","int64_value_with_default",b"int64_value_with_default","message_value",b"message_value","sfixed32_value",b"sfixed32_value","sfixed32_value_with_default",b"sfixed32_value_with_default","sfixed64_value",b"sfixed64_value","sfixed64_value_with_default",b"sfixed64_value_with_default","sint32_value",b"sint32_value","sint32_value_with_default",b"sint32_value_with_default","sint64_value",b"sint64_value","sint64_value_with_default",b"sint64_value_with_default","string_value",b"string_value","string_value_with_default",b"string_value_with_default","uint32_value",b"uint32_value","uint32_value_with_default",b"uint32_value_with_default","uint64_value",b"uint64_value","uint64_value_with_default",b"uint64_value_with_default"]) -> None: ...
global___TestValue = TestValue

class PackedTestValue(google.protobuf.message.Message):
    """A PackedTestValue looks exactly the same as a TestValue in the text format,
    but the binary serializion is different. We test the packed representations
    by loading the same test cases using this definition instead of TestValue.

    NOTE: This definition must be kept in sync with TestValue in every way except
    the packed=true declaration and the lack of extensions.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    FLOAT_VALUE_FIELD_NUMBER: builtins.int
    INT64_VALUE_FIELD_NUMBER: builtins.int
    UINT64_VALUE_FIELD_NUMBER: builtins.int
    INT32_VALUE_FIELD_NUMBER: builtins.int
    FIXED64_VALUE_FIELD_NUMBER: builtins.int
    FIXED32_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    BYTES_VALUE_FIELD_NUMBER: builtins.int
    UINT32_VALUE_FIELD_NUMBER: builtins.int
    SFIXED32_VALUE_FIELD_NUMBER: builtins.int
    SFIXED64_VALUE_FIELD_NUMBER: builtins.int
    SINT32_VALUE_FIELD_NUMBER: builtins.int
    SINT64_VALUE_FIELD_NUMBER: builtins.int
    MESSAGE_VALUE_FIELD_NUMBER: builtins.int
    ENUM_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    FLOAT_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    INT64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    UINT64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    INT32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    FIXED64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    FIXED32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    BOOL_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    STRING_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    BYTES_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    UINT32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    SFIXED32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    SFIXED64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    SINT32_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    SINT64_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    ENUM_VALUE_WITH_DEFAULT_FIELD_NUMBER: builtins.int
    @property
    def double_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def float_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def int64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def uint64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def int32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def fixed64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def fixed32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def bool_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    @property
    def string_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def bytes_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def uint32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sfixed32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sfixed64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sint32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sint64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def message_value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PrimitiveValue]: ...
    @property
    def enum_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___Color.ValueType]: ...
    double_value_with_default: builtins.float
    float_value_with_default: builtins.float
    int64_value_with_default: builtins.int
    uint64_value_with_default: builtins.int
    int32_value_with_default: builtins.int
    fixed64_value_with_default: builtins.int
    fixed32_value_with_default: builtins.int
    bool_value_with_default: builtins.bool
    string_value_with_default: typing.Text
    bytes_value_with_default: builtins.bytes
    uint32_value_with_default: builtins.int
    sfixed32_value_with_default: builtins.int
    sfixed64_value_with_default: builtins.int
    sint32_value_with_default: builtins.int
    sint64_value_with_default: builtins.int
    enum_value_with_default: global___Color.ValueType
    def __init__(self,
        *,
        double_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        float_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        int64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        uint64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        int32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        fixed64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        fixed32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        bool_value: typing.Optional[typing.Iterable[builtins.bool]] = ...,
        string_value: typing.Optional[typing.Iterable[typing.Text]] = ...,
        bytes_value: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        uint32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sfixed32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sfixed64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sint32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sint64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        message_value: typing.Optional[typing.Iterable[global___PrimitiveValue]] = ...,
        enum_value: typing.Optional[typing.Iterable[global___Color.ValueType]] = ...,
        double_value_with_default: typing.Optional[builtins.float] = ...,
        float_value_with_default: typing.Optional[builtins.float] = ...,
        int64_value_with_default: typing.Optional[builtins.int] = ...,
        uint64_value_with_default: typing.Optional[builtins.int] = ...,
        int32_value_with_default: typing.Optional[builtins.int] = ...,
        fixed64_value_with_default: typing.Optional[builtins.int] = ...,
        fixed32_value_with_default: typing.Optional[builtins.int] = ...,
        bool_value_with_default: typing.Optional[builtins.bool] = ...,
        string_value_with_default: typing.Optional[typing.Text] = ...,
        bytes_value_with_default: typing.Optional[builtins.bytes] = ...,
        uint32_value_with_default: typing.Optional[builtins.int] = ...,
        sfixed32_value_with_default: typing.Optional[builtins.int] = ...,
        sfixed64_value_with_default: typing.Optional[builtins.int] = ...,
        sint32_value_with_default: typing.Optional[builtins.int] = ...,
        sint64_value_with_default: typing.Optional[builtins.int] = ...,
        enum_value_with_default: typing.Optional[global___Color.ValueType] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bool_value_with_default",b"bool_value_with_default","bytes_value_with_default",b"bytes_value_with_default","double_value_with_default",b"double_value_with_default","enum_value_with_default",b"enum_value_with_default","fixed32_value_with_default",b"fixed32_value_with_default","fixed64_value_with_default",b"fixed64_value_with_default","float_value_with_default",b"float_value_with_default","int32_value_with_default",b"int32_value_with_default","int64_value_with_default",b"int64_value_with_default","sfixed32_value_with_default",b"sfixed32_value_with_default","sfixed64_value_with_default",b"sfixed64_value_with_default","sint32_value_with_default",b"sint32_value_with_default","sint64_value_with_default",b"sint64_value_with_default","string_value_with_default",b"string_value_with_default","uint32_value_with_default",b"uint32_value_with_default","uint64_value_with_default",b"uint64_value_with_default"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool_value",b"bool_value","bool_value_with_default",b"bool_value_with_default","bytes_value",b"bytes_value","bytes_value_with_default",b"bytes_value_with_default","double_value",b"double_value","double_value_with_default",b"double_value_with_default","enum_value",b"enum_value","enum_value_with_default",b"enum_value_with_default","fixed32_value",b"fixed32_value","fixed32_value_with_default",b"fixed32_value_with_default","fixed64_value",b"fixed64_value","fixed64_value_with_default",b"fixed64_value_with_default","float_value",b"float_value","float_value_with_default",b"float_value_with_default","int32_value",b"int32_value","int32_value_with_default",b"int32_value_with_default","int64_value",b"int64_value","int64_value_with_default",b"int64_value_with_default","message_value",b"message_value","sfixed32_value",b"sfixed32_value","sfixed32_value_with_default",b"sfixed32_value_with_default","sfixed64_value",b"sfixed64_value","sfixed64_value_with_default",b"sfixed64_value_with_default","sint32_value",b"sint32_value","sint32_value_with_default",b"sint32_value_with_default","sint64_value",b"sint64_value","sint64_value_with_default",b"sint64_value_with_default","string_value",b"string_value","string_value_with_default",b"string_value_with_default","uint32_value",b"uint32_value","uint32_value_with_default",b"uint32_value_with_default","uint64_value",b"uint64_value","uint64_value_with_default",b"uint64_value_with_default"]) -> None: ...
global___PackedTestValue = PackedTestValue

class PrimitiveValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    FLOAT_VALUE_FIELD_NUMBER: builtins.int
    INT64_VALUE_FIELD_NUMBER: builtins.int
    UINT64_VALUE_FIELD_NUMBER: builtins.int
    INT32_VALUE_FIELD_NUMBER: builtins.int
    FIXED64_VALUE_FIELD_NUMBER: builtins.int
    FIXED32_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    BYTES_VALUE_FIELD_NUMBER: builtins.int
    UINT32_VALUE_FIELD_NUMBER: builtins.int
    SFIXED32_VALUE_FIELD_NUMBER: builtins.int
    SFIXED64_VALUE_FIELD_NUMBER: builtins.int
    SINT32_VALUE_FIELD_NUMBER: builtins.int
    SINT64_VALUE_FIELD_NUMBER: builtins.int
    double_value: builtins.float
    float_value: builtins.float
    int64_value: builtins.int
    uint64_value: builtins.int
    int32_value: builtins.int
    fixed64_value: builtins.int
    fixed32_value: builtins.int
    bool_value: builtins.bool
    string_value: typing.Text
    bytes_value: builtins.bytes
    uint32_value: builtins.int
    sfixed32_value: builtins.int
    sfixed64_value: builtins.int
    sint32_value: builtins.int
    sint64_value: builtins.int
    def __init__(self,
        *,
        double_value: typing.Optional[builtins.float] = ...,
        float_value: typing.Optional[builtins.float] = ...,
        int64_value: typing.Optional[builtins.int] = ...,
        uint64_value: typing.Optional[builtins.int] = ...,
        int32_value: typing.Optional[builtins.int] = ...,
        fixed64_value: typing.Optional[builtins.int] = ...,
        fixed32_value: typing.Optional[builtins.int] = ...,
        bool_value: typing.Optional[builtins.bool] = ...,
        string_value: typing.Optional[typing.Text] = ...,
        bytes_value: typing.Optional[builtins.bytes] = ...,
        uint32_value: typing.Optional[builtins.int] = ...,
        sfixed32_value: typing.Optional[builtins.int] = ...,
        sfixed64_value: typing.Optional[builtins.int] = ...,
        sint32_value: typing.Optional[builtins.int] = ...,
        sint64_value: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bool_value",b"bool_value","bytes_value",b"bytes_value","double_value",b"double_value","fixed32_value",b"fixed32_value","fixed64_value",b"fixed64_value","float_value",b"float_value","int32_value",b"int32_value","int64_value",b"int64_value","sfixed32_value",b"sfixed32_value","sfixed64_value",b"sfixed64_value","sint32_value",b"sint32_value","sint64_value",b"sint64_value","string_value",b"string_value","uint32_value",b"uint32_value","uint64_value",b"uint64_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool_value",b"bool_value","bytes_value",b"bytes_value","double_value",b"double_value","fixed32_value",b"fixed32_value","fixed64_value",b"fixed64_value","float_value",b"float_value","int32_value",b"int32_value","int64_value",b"int64_value","sfixed32_value",b"sfixed32_value","sfixed64_value",b"sfixed64_value","sint32_value",b"sint32_value","sint64_value",b"sint64_value","string_value",b"string_value","uint32_value",b"uint32_value","uint64_value",b"uint64_value"]) -> None: ...
global___PrimitiveValue = PrimitiveValue

class ExtraFields(google.protobuf.message.Message):
    """Message containing fields with field numbers higher than any field above.
    An instance of this message is prepended to each binary message in the test
    to exercise the code path that handles fields encoded out of order of field
    number.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    STRING_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    string_value: typing.Text
    bool_value: builtins.bool
    def __init__(self,
        *,
        string_value: typing.Optional[typing.Text] = ...,
        bool_value: typing.Optional[builtins.bool] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bool_value",b"bool_value","string_value",b"string_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool_value",b"bool_value","string_value",b"string_value"]) -> None: ...
global___ExtraFields = ExtraFields

class InnerMessageValue(google.protobuf.message.Message):
    """The messages below are for yet-to-be created tests.

    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FLOAT_VALUE_FIELD_NUMBER: builtins.int
    BYTES_VALUES_FIELD_NUMBER: builtins.int
    float_value: builtins.float
    @property
    def bytes_values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(self,
        *,
        float_value: typing.Optional[builtins.float] = ...,
        bytes_values: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["float_value",b"float_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bytes_values",b"bytes_values","float_value",b"float_value"]) -> None: ...
global___InnerMessageValue = InnerMessageValue

class MiddleMessageValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    INT32_VALUES_FIELD_NUMBER: builtins.int
    MESSAGE_VALUE_FIELD_NUMBER: builtins.int
    UINT32_VALUE_FIELD_NUMBER: builtins.int
    @property
    def int32_values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def message_value(self) -> global___InnerMessageValue: ...
    uint32_value: builtins.int
    def __init__(self,
        *,
        int32_values: typing.Optional[typing.Iterable[builtins.int]] = ...,
        message_value: typing.Optional[global___InnerMessageValue] = ...,
        uint32_value: typing.Optional[builtins.int] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["message_value",b"message_value","uint32_value",b"uint32_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["int32_values",b"int32_values","message_value",b"message_value","uint32_value",b"uint32_value"]) -> None: ...
global___MiddleMessageValue = MiddleMessageValue

class MessageValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    MESSAGE_VALUE_FIELD_NUMBER: builtins.int
    double_value: builtins.float
    @property
    def message_value(self) -> global___MiddleMessageValue: ...
    def __init__(self,
        *,
        double_value: typing.Optional[builtins.float] = ...,
        message_value: typing.Optional[global___MiddleMessageValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["double_value",b"double_value","message_value",b"message_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["double_value",b"double_value","message_value",b"message_value"]) -> None: ...
global___MessageValue = MessageValue

class RepeatedMessageValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class NestedMessageValue(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        FLOAT_VALUE_FIELD_NUMBER: builtins.int
        BYTES_VALUES_FIELD_NUMBER: builtins.int
        float_value: builtins.float
        @property
        def bytes_values(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
        def __init__(self,
            *,
            float_value: typing.Optional[builtins.float] = ...,
            bytes_values: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["float_value",b"float_value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["bytes_values",b"bytes_values","float_value",b"float_value"]) -> None: ...

    MESSAGE_VALUES_FIELD_NUMBER: builtins.int
    @property
    def message_values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RepeatedMessageValue.NestedMessageValue]: ...
    def __init__(self,
        *,
        message_values: typing.Optional[typing.Iterable[global___RepeatedMessageValue.NestedMessageValue]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["message_values",b"message_values"]) -> None: ...
global___RepeatedMessageValue = RepeatedMessageValue

EXT_VALUE_FIELD_NUMBER: builtins.int
ext_value: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[global___TestValue, google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PrimitiveValue]]
