"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import tensorflow.core.framework.tensor_shape_pb2
import tensorflow.core.framework.types_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class TensorMetadata(google.protobuf.message.Message):
    """TensorMetadata indicates the type and shape of a Tensor that is
    part of a host compute transfer.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    type: tensorflow.core.framework.types_pb2.DataType.ValueType
    @property
    def shape(self) -> tensorflow.core.framework.tensor_shape_pb2.TensorShapeProto: ...
    def __init__(self,
        *,
        type: tensorflow.core.framework.types_pb2.DataType.ValueType = ...,
        shape: typing.Optional[tensorflow.core.framework.tensor_shape_pb2.TensorShapeProto] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["shape",b"shape"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["shape",b"shape","type",b"type"]) -> None: ...
global___TensorMetadata = TensorMetadata

class HostTransferMetadata(google.protobuf.message.Message):
    """HostTransferMetadata describes a transfer either from host to device
    or device to host. It has a key that is unique to the computation,
    and metadata about the list of tensors being transferred.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    key: typing.Text
    """The key used to identify this transfer."""

    @property
    def metadata(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TensorMetadata]:
        """For each Tensor being transferred, its type and shape."""
        pass
    def __init__(self,
        *,
        key: typing.Text = ...,
        metadata: typing.Optional[typing.Iterable[global___TensorMetadata]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key",b"key","metadata",b"metadata"]) -> None: ...
global___HostTransferMetadata = HostTransferMetadata

class HostComputeMetadata(google.protobuf.message.Message):
    """HostComputeMetadata describes all the sends and recvs
    from all host compute transfer ops in a computation.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEVICE_TO_HOST_FIELD_NUMBER: builtins.int
    HOST_TO_DEVICE_FIELD_NUMBER: builtins.int
    @property
    def device_to_host(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HostTransferMetadata]:
        """Metadata about each device_to_host transfer"""
        pass
    @property
    def host_to_device(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___HostTransferMetadata]:
        """Metadata about each host_to_device transfer"""
        pass
    def __init__(self,
        *,
        device_to_host: typing.Optional[typing.Iterable[global___HostTransferMetadata]] = ...,
        host_to_device: typing.Optional[typing.Iterable[global___HostTransferMetadata]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["device_to_host",b"device_to_host","host_to_device",b"host_to_device"]) -> None: ...
global___HostComputeMetadata = HostComputeMetadata
