# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/debug/debug_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pythie_serving.tensorflow_proto.tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
from pythie_serving.tensorflow_proto.tensorflow.core.profiler import tfprof_log_pb2 as tensorflow_dot_core_dot_profiler_dot_tfprof__log__pb2
from pythie_serving.tensorflow_proto.tensorflow.core.protobuf import debug_pb2 as tensorflow_dot_core_dot_protobuf_dot_debug__pb2
from pythie_serving.tensorflow_proto.tensorflow.core.util import event_pb2 as tensorflow_dot_core_dot_util_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)tensorflow/core/debug/debug_service.proto\x12\ntensorflow\x1a&tensorflow/core/framework/tensor.proto\x1a)tensorflow/core/profiler/tfprof_log.proto\x1a$tensorflow/core/protobuf/debug.proto\x1a tensorflow/core/util/event.proto\"\xde\x02\n\nEventReply\x12I\n\x16\x64\x65\x62ug_op_state_changes\x18\x01 \x03(\x0b\x32).tensorflow.EventReply.DebugOpStateChange\x12\'\n\x06tensor\x18\x02 \x01(\x0b\x32\x17.tensorflow.TensorProto\x1a\xdb\x01\n\x12\x44\x65\x62ugOpStateChange\x12>\n\x05state\x18\x01 \x01(\x0e\x32/.tensorflow.EventReply.DebugOpStateChange.State\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x13\n\x0boutput_slot\x18\x03 \x01(\x05\x12\x10\n\x08\x64\x65\x62ug_op\x18\x04 \x01(\t\"K\n\x05State\x12\x15\n\x11STATE_UNSPECIFIED\x10\x00\x12\x0c\n\x08\x44ISABLED\x10\x01\x12\r\n\tREAD_ONLY\x10\x02\x12\x0e\n\nREAD_WRITE\x10\x03\"\xa7\x03\n\rCallTraceback\x12\x35\n\tcall_type\x18\x01 \x01(\x0e\x32\".tensorflow.CallTraceback.CallType\x12\x10\n\x08\x63\x61ll_key\x18\x02 \x01(\t\x12\x30\n\x0corigin_stack\x18\x03 \x01(\x0b\x32\x1a.tensorflow.tfprof.CodeDef\x12L\n\x13origin_id_to_string\x18\x04 \x03(\x0b\x32/.tensorflow.CallTraceback.OriginIdToStringEntry\x12\x36\n\x0fgraph_traceback\x18\x05 \x01(\x0b\x32\x1d.tensorflow.tfprof.OpLogProto\x12\x15\n\rgraph_version\x18\x06 \x01(\x03\x1a\x37\n\x15OriginIdToStringEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"E\n\x08\x43\x61llType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x13\n\x0fGRAPH_EXECUTION\x10\x01\x12\x13\n\x0f\x45\x41GER_EXECUTION\x10\x02\x32\xdd\x01\n\rEventListener\x12;\n\nSendEvents\x12\x11.tensorflow.Event\x1a\x16.tensorflow.EventReply(\x01\x30\x01\x12\x43\n\x0eSendTracebacks\x12\x19.tensorflow.CallTraceback\x1a\x16.tensorflow.EventReply\x12J\n\x0fSendSourceFiles\x12\x1f.tensorflow.DebuggedSourceFiles\x1a\x16.tensorflow.EventReplyb\x06proto3')



_EVENTREPLY = DESCRIPTOR.message_types_by_name['EventReply']
_EVENTREPLY_DEBUGOPSTATECHANGE = _EVENTREPLY.nested_types_by_name['DebugOpStateChange']
_CALLTRACEBACK = DESCRIPTOR.message_types_by_name['CallTraceback']
_CALLTRACEBACK_ORIGINIDTOSTRINGENTRY = _CALLTRACEBACK.nested_types_by_name['OriginIdToStringEntry']
_EVENTREPLY_DEBUGOPSTATECHANGE_STATE = _EVENTREPLY_DEBUGOPSTATECHANGE.enum_types_by_name['State']
_CALLTRACEBACK_CALLTYPE = _CALLTRACEBACK.enum_types_by_name['CallType']
EventReply = _reflection.GeneratedProtocolMessageType('EventReply', (_message.Message,), {

  'DebugOpStateChange' : _reflection.GeneratedProtocolMessageType('DebugOpStateChange', (_message.Message,), {
    'DESCRIPTOR' : _EVENTREPLY_DEBUGOPSTATECHANGE,
    '__module__' : 'tensorflow.core.debug.debug_service_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.EventReply.DebugOpStateChange)
    })
  ,
  'DESCRIPTOR' : _EVENTREPLY,
  '__module__' : 'tensorflow.core.debug.debug_service_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.EventReply)
  })
_sym_db.RegisterMessage(EventReply)
_sym_db.RegisterMessage(EventReply.DebugOpStateChange)

CallTraceback = _reflection.GeneratedProtocolMessageType('CallTraceback', (_message.Message,), {

  'OriginIdToStringEntry' : _reflection.GeneratedProtocolMessageType('OriginIdToStringEntry', (_message.Message,), {
    'DESCRIPTOR' : _CALLTRACEBACK_ORIGINIDTOSTRINGENTRY,
    '__module__' : 'tensorflow.core.debug.debug_service_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.CallTraceback.OriginIdToStringEntry)
    })
  ,
  'DESCRIPTOR' : _CALLTRACEBACK,
  '__module__' : 'tensorflow.core.debug.debug_service_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.CallTraceback)
  })
_sym_db.RegisterMessage(CallTraceback)
_sym_db.RegisterMessage(CallTraceback.OriginIdToStringEntry)

_EVENTLISTENER = DESCRIPTOR.services_by_name['EventListener']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALLTRACEBACK_ORIGINIDTOSTRINGENTRY._options = None
  _CALLTRACEBACK_ORIGINIDTOSTRINGENTRY._serialized_options = b'8\001'
  _EVENTREPLY._serialized_start=213
  _EVENTREPLY._serialized_end=563
  _EVENTREPLY_DEBUGOPSTATECHANGE._serialized_start=344
  _EVENTREPLY_DEBUGOPSTATECHANGE._serialized_end=563
  _EVENTREPLY_DEBUGOPSTATECHANGE_STATE._serialized_start=488
  _EVENTREPLY_DEBUGOPSTATECHANGE_STATE._serialized_end=563
  _CALLTRACEBACK._serialized_start=566
  _CALLTRACEBACK._serialized_end=989
  _CALLTRACEBACK_ORIGINIDTOSTRINGENTRY._serialized_start=863
  _CALLTRACEBACK_ORIGINIDTOSTRINGENTRY._serialized_end=918
  _CALLTRACEBACK_CALLTYPE._serialized_start=920
  _CALLTRACEBACK_CALLTYPE._serialized_end=989
  _EVENTLISTENER._serialized_start=992
  _EVENTLISTENER._serialized_end=1213
# @@protoc_insertion_point(module_scope)
