# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_serving/util/class_registration_test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5tensorflow_serving/util/class_registration_test.proto\x12\x12tensorflow.serving\x1a\x19google/protobuf/any.proto\"\x1f\n\x07\x43onfig1\x12\x14\n\x0cstring_field\x18\x01 \x01(\t\"\x1f\n\x07\x43onfig2\x12\x14\n\x0cstring_field\x18\x01 \x01(\t\"9\n\x0eMessageWithAny\x12\'\n\tany_field\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensorflow_serving.util.class_registration_test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONFIG1._serialized_start=104
  _CONFIG1._serialized_end=135
  _CONFIG2._serialized_start=137
  _CONFIG2._serialized_end=168
  _MESSAGEWITHANY._serialized_start=170
  _MESSAGEWITHANY._serialized_end=227
# @@protoc_insertion_point(module_scope)
