# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/tpu/dynamic_padding.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2tensorflow/core/protobuf/tpu/dynamic_padding.proto\x12\x0etensorflow.tpu\"O\n\nPaddingMap\x12\x11\n\targ_index\x18\x01 \x01(\x05\x12\x13\n\x0bshape_index\x18\x02 \x01(\x05\x12\x19\n\x11padding_arg_index\x18\x03 \x01(\x05\x42\x03\xf8\x01\x01\x62\x06proto3')



_PADDINGMAP = DESCRIPTOR.message_types_by_name['PaddingMap']
PaddingMap = _reflection.GeneratedProtocolMessageType('PaddingMap', (_message.Message,), {
  'DESCRIPTOR' : _PADDINGMAP,
  '__module__' : 'tensorflow.core.protobuf.tpu.dynamic_padding_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.tpu.PaddingMap)
  })
_sym_db.RegisterMessage(PaddingMap)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _PADDINGMAP._serialized_start=70
  _PADDINGMAP._serialized_end=149
# @@protoc_insertion_point(module_scope)
