# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/protobuf/conv_autotuning.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pythie_serving.tensorflow_proto.tensorflow.stream_executor import dnn_pb2 as tensorflow_dot_stream__executor_dot_dnn__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.tensorflow/core/protobuf/conv_autotuning.proto\x12\ntensorflow\x1a$tensorflow/stream_executor/dnn.proto\"\x9d\x04\n\x10\x43onvolutionProto\x12\x32\n\x04kind\x18\x01 \x01(\x0e\x32$.stream_executor.dnn.ConvolutionKind\x12\x39\n\x05input\x18\x02 \x01(\x0b\x32*.stream_executor.dnn.TensorDescriptorProto\x12:\n\x06\x66ilter\x18\x03 \x01(\x0b\x32*.stream_executor.dnn.TensorDescriptorProto\x12:\n\x06output\x18\x04 \x01(\x0b\x32*.stream_executor.dnn.TensorDescriptorProto\x12\x42\n\tconv_desc\x18\x05 \x01(\x0b\x32/.stream_executor.dnn.ConvolutionDescriptorProto\x12\x12\n\nconv_scale\x18\x06 \x01(\x01\x12\x18\n\x10side_value_scale\x18\x07 \x01(\x01\x12\x37\n\nactivation\x18\x08 \x01(\x0e\x32#.stream_executor.dnn.ActivationMode\x12\x15\n\rinput_address\x18\t \x01(\x03\x12\x16\n\x0e\x66ilter_address\x18\n \x01(\x03\x12\x16\n\x0eoutput_address\x18\x0b \x01(\x03\x12\x14\n\x0c\x62ias_address\x18\x0c \x01(\x03\x12\x1a\n\x12side_input_address\x18\r \x01(\x03\x42WZUgithub.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_protob\x06proto3')



_CONVOLUTIONPROTO = DESCRIPTOR.message_types_by_name['ConvolutionProto']
ConvolutionProto = _reflection.GeneratedProtocolMessageType('ConvolutionProto', (_message.Message,), {
  'DESCRIPTOR' : _CONVOLUTIONPROTO,
  '__module__' : 'tensorflow.core.protobuf.conv_autotuning_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.ConvolutionProto)
  })
_sym_db.RegisterMessage(ConvolutionProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZUgithub.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto'
  _CONVOLUTIONPROTO._serialized_start=101
  _CONVOLUTIONPROTO._serialized_end=642
# @@protoc_insertion_point(module_scope)
