# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pythie_serving.tensorflow_proto.tensorflow.core.data.service import dispatcher_pb2 as tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2


class DispatcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WorkerHeartbeat = channel.unary_unary(
                '/tensorflow.data.DispatcherService/WorkerHeartbeat',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerHeartbeatRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerHeartbeatResponse.FromString,
                )
        self.WorkerUpdate = channel.unary_unary(
                '/tensorflow.data.DispatcherService/WorkerUpdate',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateResponse.FromString,
                )
        self.GetDatasetDef = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetDatasetDef',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetDatasetDefRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetDatasetDefResponse.FromString,
                )
        self.GetSplit = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetSplit',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetSplitRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetSplitResponse.FromString,
                )
        self.GetVersion = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetVersion',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetVersionRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetVersionResponse.FromString,
                )
        self.GetOrRegisterDataset = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetOrRegisterDataset',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetResponse.FromString,
                )
        self.GetOrCreateJob = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetOrCreateJob',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobResponse.FromString,
                )
        self.MaybeRemoveTask = channel.unary_unary(
                '/tensorflow.data.DispatcherService/MaybeRemoveTask',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.MaybeRemoveTaskRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.MaybeRemoveTaskResponse.FromString,
                )
        self.ReleaseJobClient = channel.unary_unary(
                '/tensorflow.data.DispatcherService/ReleaseJobClient',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ReleaseJobClientRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ReleaseJobClientResponse.FromString,
                )
        self.ClientHeartbeat = channel.unary_unary(
                '/tensorflow.data.DispatcherService/ClientHeartbeat',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ClientHeartbeatRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ClientHeartbeatResponse.FromString,
                )
        self.GetWorkers = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetWorkers',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersResponse.FromString,
                )


class DispatcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WorkerHeartbeat(self, request, context):
        """Performs a periodic worker heartbeat.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkerUpdate(self, request, context):
        """Updates the dispatcher with information about the worker's state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDatasetDef(self, request, context):
        """Gets a dataset defintion.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSplit(self, request, context):
        """Gets the next split for a given job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Returns the API version of the server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrRegisterDataset(self, request, context):
        """Registers a dataset with the server, or returns its id if it is already
        registered.

        The dataset is constructed in a new graph, so it must not refer to
        external resources or variables.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrCreateJob(self, request, context):
        """Gets a job if it already exists, otherwise creates it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MaybeRemoveTask(self, request, context):
        """Attempts to remove a task from a round-robin read job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseJobClient(self, request, context):
        """Releases a job client so that a job may eventually be cleaned up.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientHeartbeat(self, request, context):
        """Heartbeats from the client. This lets the dispatcher know that the client
        is still active, and gives the dispatcher a chance to notify the client
        of new tasks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkers(self, request, context):
        """Reports a list of all workers registered with the dispatcher.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WorkerHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerHeartbeat,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerHeartbeatRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerHeartbeatResponse.SerializeToString,
            ),
            'WorkerUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerUpdate,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateResponse.SerializeToString,
            ),
            'GetDatasetDef': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDatasetDef,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetDatasetDefRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetDatasetDefResponse.SerializeToString,
            ),
            'GetSplit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSplit,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetSplitRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetSplitResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetVersionRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetVersionResponse.SerializeToString,
            ),
            'GetOrRegisterDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrRegisterDataset,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetResponse.SerializeToString,
            ),
            'GetOrCreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrCreateJob,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobResponse.SerializeToString,
            ),
            'MaybeRemoveTask': grpc.unary_unary_rpc_method_handler(
                    servicer.MaybeRemoveTask,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.MaybeRemoveTaskRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.MaybeRemoveTaskResponse.SerializeToString,
            ),
            'ReleaseJobClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseJobClient,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ReleaseJobClientRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ReleaseJobClientResponse.SerializeToString,
            ),
            'ClientHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientHeartbeat,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ClientHeartbeatRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ClientHeartbeatResponse.SerializeToString,
            ),
            'GetWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkers,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensorflow.data.DispatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DispatcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WorkerHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/WorkerHeartbeat',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerHeartbeatRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerHeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WorkerUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/WorkerUpdate',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDatasetDef(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetDatasetDef',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetDatasetDefRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetDatasetDefResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSplit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetSplit',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetSplitRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetSplitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetVersion',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetVersionRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetVersionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrRegisterDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetOrRegisterDataset',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrCreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetOrCreateJob',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MaybeRemoveTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/MaybeRemoveTask',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.MaybeRemoveTaskRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.MaybeRemoveTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseJobClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/ReleaseJobClient',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ReleaseJobClientRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ReleaseJobClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/ClientHeartbeat',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ClientHeartbeatRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.ClientHeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetWorkers',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
