# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pythie_serving.tensorflow_proto.tensorflow.core.data.service import dispatcher_pb2 as tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2


class DispatcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/tensorflow.data.DispatcherService/RegisterWorker',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.RegisterWorkerResponse.FromString,
                )
        self.WorkerUpdate = channel.unary_unary(
                '/tensorflow.data.DispatcherService/WorkerUpdate',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateResponse.FromString,
                )
        self.GetOrRegisterDataset = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetOrRegisterDataset',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetResponse.FromString,
                )
        self.GetOrCreateJob = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetOrCreateJob',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobResponse.FromString,
                )
        self.CreateJob = channel.unary_unary(
                '/tensorflow.data.DispatcherService/CreateJob',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.CreateJobResponse.FromString,
                )
        self.GetTasks = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetTasks',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetTasksRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetTasksResponse.FromString,
                )
        self.GetWorkers = channel.unary_unary(
                '/tensorflow.data.DispatcherService/GetWorkers',
                request_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersRequest.SerializeToString,
                response_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersResponse.FromString,
                )


class DispatcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterWorker(self, request, context):
        """Registers a worker with the dispatcher.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WorkerUpdate(self, request, context):
        """Updates the dispatcher with information about the worker's state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrRegisterDataset(self, request, context):
        """Registers a dataset with the server, or returns its id if it is already
        registered.

        The dataset is constructed in a new graph, so it must not refer to
        external resources or variables.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrCreateJob(self, request, context):
        """Gets a job if it already exists, otherwise creates it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJob(self, request, context):
        """Creates a job for reading from the tf.data service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTasks(self, request, context):
        """Reports a list of all tasks for a job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkers(self, request, context):
        """Reports a list of all workers registered with the dispatcher.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'WorkerUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.WorkerUpdate,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateResponse.SerializeToString,
            ),
            'GetOrRegisterDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrRegisterDataset,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetResponse.SerializeToString,
            ),
            'GetOrCreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrCreateJob,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobResponse.SerializeToString,
            ),
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.CreateJobRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.CreateJobResponse.SerializeToString,
            ),
            'GetTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTasks,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetTasksRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetTasksResponse.SerializeToString,
            ),
            'GetWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkers,
                    request_deserializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersRequest.FromString,
                    response_serializer=tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensorflow.data.DispatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DispatcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/RegisterWorker',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.RegisterWorkerRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.RegisterWorkerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WorkerUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/WorkerUpdate',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.WorkerUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrRegisterDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetOrRegisterDataset',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrRegisterDatasetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrCreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetOrCreateJob',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetOrCreateJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/CreateJob',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.CreateJobRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.CreateJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetTasks',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetTasksRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetTasksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.data.DispatcherService/GetWorkers',
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersRequest.SerializeToString,
            tensorflow_dot_core_dot_data_dot_service_dot_dispatcher__pb2.GetWorkersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
