# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_serving/config/logging_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pythie_serving.tensorflow_proto.tensorflow_serving.config import log_collector_config_pb2 as tensorflow__serving_dot_config_dot_log__collector__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.tensorflow_serving/config/logging_config.proto\x12\x12tensorflow.serving\x1a\x34tensorflow_serving/config/log_collector_config.proto\"\'\n\x0eSamplingConfig\x12\x15\n\rsampling_rate\x18\x01 \x01(\x01\"\x92\x01\n\rLoggingConfig\x12\x44\n\x14log_collector_config\x18\x01 \x01(\x0b\x32&.tensorflow.serving.LogCollectorConfig\x12;\n\x0fsampling_config\x18\x02 \x01(\x0b\x32\".tensorflow.serving.SamplingConfigB\x03\xf8\x01\x01\x62\x06proto3')



_SAMPLINGCONFIG = DESCRIPTOR.message_types_by_name['SamplingConfig']
_LOGGINGCONFIG = DESCRIPTOR.message_types_by_name['LoggingConfig']
SamplingConfig = _reflection.GeneratedProtocolMessageType('SamplingConfig', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLINGCONFIG,
  '__module__' : 'tensorflow_serving.config.logging_config_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.serving.SamplingConfig)
  })
_sym_db.RegisterMessage(SamplingConfig)

LoggingConfig = _reflection.GeneratedProtocolMessageType('LoggingConfig', (_message.Message,), {
  'DESCRIPTOR' : _LOGGINGCONFIG,
  '__module__' : 'tensorflow_serving.config.logging_config_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.serving.LoggingConfig)
  })
_sym_db.RegisterMessage(LoggingConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _SAMPLINGCONFIG._serialized_start=124
  _SAMPLINGCONFIG._serialized_end=163
  _LOGGINGCONFIG._serialized_start=166
  _LOGGINGCONFIG._serialized_end=312
# @@protoc_insertion_point(module_scope)
