"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import tensorflow.core.function.trace_type.serialization_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class MyCustomRepresentation(google.protobuf.message.Message):
    """Represents a class with just two fields."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INDEX_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    index: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        index: builtins.int | None = ...,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["index", b"index", "name", b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["index", b"index", "name", b"name"]) -> None: ...

global___MyCustomRepresentation = MyCustomRepresentation

@typing_extensions.final
class MyCompositeRepresentation(google.protobuf.message.Message):
    """Represents a class that is composed of multiple SerializedTraceType objects."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ELEMENTS_FIELD_NUMBER: builtins.int
    @property
    def elements(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[tensorflow.core.function.trace_type.serialization_pb2.SerializedTraceType]: ...
    def __init__(
        self,
        *,
        elements: collections.abc.Iterable[tensorflow.core.function.trace_type.serialization_pb2.SerializedTraceType] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["elements", b"elements"]) -> None: ...

global___MyCompositeRepresentation = MyCompositeRepresentation

@typing_extensions.final
class MyMultiClassRepresentation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["id", b"id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id", b"id"]) -> None: ...

global___MyMultiClassRepresentation = MyMultiClassRepresentation
