# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/security/fuzzing/checkpoint_reader_fuzz_input.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pythie_serving.tensorflow_proto.tensorflow.core.util import saved_tensor_slice_pb2 as tensorflow_dot_core_dot_util_dot_saved__tensor__slice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>tensorflow/security/fuzzing/checkpoint_reader_fuzz_input.proto\x12\ntensorflow\x1a-tensorflow/core/util/saved_tensor_slice.proto\"q\n\x19\x43heckpointReaderFuzzInput\x12.\n\x04meta\x18\x01 \x01(\x0b\x32 .tensorflow.SavedTensorSliceMeta\x12$\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x16.tensorflow.SavedSliceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tensorflow.security.fuzzing.checkpoint_reader_fuzz_input_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKPOINTREADERFUZZINPUT._serialized_start=125
  _CHECKPOINTREADERFUZZINPUT._serialized_end=238
# @@protoc_insertion_point(module_scope)
