"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import tensorflow.core.framework.tensor_pb2
import tensorflow.core.framework.tensor_shape_pb2
import tensorflow.core.framework.tensor_slice_pb2
import tensorflow.core.framework.types_pb2
import tensorflow.core.framework.versions_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class SavedSliceMeta(google.protobuf.message.Message):
    """Metadata describing the set of slices of the same tensor saved in a
    checkpoint file.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SLICE_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Name of the tensor."""

    @property
    def shape(self) -> tensorflow.core.framework.tensor_shape_pb2.TensorShapeProto:
        """Shape of the tensor"""
        pass
    type: tensorflow.core.framework.types_pb2.DataType.ValueType
    """Type of the tensor"""

    @property
    def slice(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[tensorflow.core.framework.tensor_slice_pb2.TensorSliceProto]:
        """Explicit list of slices saved in the checkpoint file."""
        pass
    def __init__(self,
        *,
        name: typing.Text = ...,
        shape: typing.Optional[tensorflow.core.framework.tensor_shape_pb2.TensorShapeProto] = ...,
        type: tensorflow.core.framework.types_pb2.DataType.ValueType = ...,
        slice: typing.Optional[typing.Iterable[tensorflow.core.framework.tensor_slice_pb2.TensorSliceProto]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["shape",b"shape"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["name",b"name","shape",b"shape","slice",b"slice","type",b"type"]) -> None: ...
global___SavedSliceMeta = SavedSliceMeta

class SavedTensorSliceMeta(google.protobuf.message.Message):
    """Metadata describing the set of tensor slices saved in a checkpoint file.
    It is always stored at the beginning of each checkpoint file.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TENSOR_FIELD_NUMBER: builtins.int
    VERSIONS_FIELD_NUMBER: builtins.int
    @property
    def tensor(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SavedSliceMeta]:
        """Each SavedSliceMeta describes the slices for one tensor."""
        pass
    @property
    def versions(self) -> tensorflow.core.framework.versions_pb2.VersionDef:
        """Compatibility version of this checkpoint.  See core/public/version.h
        for version history.
        """
        pass
    def __init__(self,
        *,
        tensor: typing.Optional[typing.Iterable[global___SavedSliceMeta]] = ...,
        versions: typing.Optional[tensorflow.core.framework.versions_pb2.VersionDef] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["versions",b"versions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["tensor",b"tensor","versions",b"versions"]) -> None: ...
global___SavedTensorSliceMeta = SavedTensorSliceMeta

class SavedSlice(google.protobuf.message.Message):
    """Saved tensor slice: it stores the name of the tensors, the slice, and the
    raw data.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    SLICE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Name of the tensor that this slice belongs to. This must be identical to
    the name used to encode the key for this record.
    """

    @property
    def slice(self) -> tensorflow.core.framework.tensor_slice_pb2.TensorSliceProto:
        """Extent of the slice.  Must have one entry for each of the dimension of the
        tensor that this slice belongs to.
        """
        pass
    @property
    def data(self) -> tensorflow.core.framework.tensor_pb2.TensorProto:
        """The raw data of the slice is stored as a TensorProto. Only raw data are
        stored (we don't fill in fields such as dtype or tensor_shape).
        """
        pass
    def __init__(self,
        *,
        name: typing.Text = ...,
        slice: typing.Optional[tensorflow.core.framework.tensor_slice_pb2.TensorSliceProto] = ...,
        data: typing.Optional[tensorflow.core.framework.tensor_pb2.TensorProto] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","slice",b"slice"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","name",b"name","slice",b"slice"]) -> None: ...
global___SavedSlice = SavedSlice

class SavedTensorSlices(google.protobuf.message.Message):
    """Each record in a v3 checkpoint file is a serialized SavedTensorSlices
    message.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    META_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def meta(self) -> global___SavedTensorSliceMeta:
        """This is only present at the first item of each checkpoint file and serves
        as a table of contents, listing all the tensor slices saved in this file.
        """
        pass
    @property
    def data(self) -> global___SavedSlice:
        """This exists in all but the first item of each checkpoint file."""
        pass
    def __init__(self,
        *,
        meta: typing.Optional[global___SavedTensorSliceMeta] = ...,
        data: typing.Optional[global___SavedSlice] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","meta",b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","meta",b"meta"]) -> None: ...
global___SavedTensorSlices = SavedTensorSlices
