"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class OptionsProto(google.protobuf.message.Message):
    """Refers to tfprof_options.h/cc for documentation.
    Only used to pass tfprof options from Python to C++.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MAX_DEPTH_FIELD_NUMBER: builtins.int
    MIN_BYTES_FIELD_NUMBER: builtins.int
    MIN_PEAK_BYTES_FIELD_NUMBER: builtins.int
    MIN_RESIDUAL_BYTES_FIELD_NUMBER: builtins.int
    MIN_OUTPUT_BYTES_FIELD_NUMBER: builtins.int
    MIN_MICROS_FIELD_NUMBER: builtins.int
    MIN_ACCELERATOR_MICROS_FIELD_NUMBER: builtins.int
    MIN_CPU_MICROS_FIELD_NUMBER: builtins.int
    MIN_PARAMS_FIELD_NUMBER: builtins.int
    MIN_FLOAT_OPS_FIELD_NUMBER: builtins.int
    MIN_OCCURRENCE_FIELD_NUMBER: builtins.int
    STEP_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    ACCOUNT_TYPE_REGEXES_FIELD_NUMBER: builtins.int
    START_NAME_REGEXES_FIELD_NUMBER: builtins.int
    TRIM_NAME_REGEXES_FIELD_NUMBER: builtins.int
    SHOW_NAME_REGEXES_FIELD_NUMBER: builtins.int
    HIDE_NAME_REGEXES_FIELD_NUMBER: builtins.int
    ACCOUNT_DISPLAYED_OP_ONLY_FIELD_NUMBER: builtins.int
    SELECT_FIELD_NUMBER: builtins.int
    OUTPUT_FIELD_NUMBER: builtins.int
    DUMP_TO_FILE_FIELD_NUMBER: builtins.int
    max_depth: builtins.int
    min_bytes: builtins.int
    min_peak_bytes: builtins.int
    min_residual_bytes: builtins.int
    min_output_bytes: builtins.int
    min_micros: builtins.int
    min_accelerator_micros: builtins.int
    min_cpu_micros: builtins.int
    min_params: builtins.int
    min_float_ops: builtins.int
    min_occurrence: builtins.int
    step: builtins.int
    order_by: typing.Text
    @property
    def account_type_regexes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def start_name_regexes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def trim_name_regexes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def show_name_regexes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def hide_name_regexes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    account_displayed_op_only: builtins.bool
    @property
    def select(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    output: typing.Text
    dump_to_file: typing.Text
    def __init__(self,
        *,
        max_depth: builtins.int = ...,
        min_bytes: builtins.int = ...,
        min_peak_bytes: builtins.int = ...,
        min_residual_bytes: builtins.int = ...,
        min_output_bytes: builtins.int = ...,
        min_micros: builtins.int = ...,
        min_accelerator_micros: builtins.int = ...,
        min_cpu_micros: builtins.int = ...,
        min_params: builtins.int = ...,
        min_float_ops: builtins.int = ...,
        min_occurrence: builtins.int = ...,
        step: builtins.int = ...,
        order_by: typing.Text = ...,
        account_type_regexes: typing.Optional[typing.Iterable[typing.Text]] = ...,
        start_name_regexes: typing.Optional[typing.Iterable[typing.Text]] = ...,
        trim_name_regexes: typing.Optional[typing.Iterable[typing.Text]] = ...,
        show_name_regexes: typing.Optional[typing.Iterable[typing.Text]] = ...,
        hide_name_regexes: typing.Optional[typing.Iterable[typing.Text]] = ...,
        account_displayed_op_only: builtins.bool = ...,
        select: typing.Optional[typing.Iterable[typing.Text]] = ...,
        output: typing.Text = ...,
        dump_to_file: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["account_displayed_op_only",b"account_displayed_op_only","account_type_regexes",b"account_type_regexes","dump_to_file",b"dump_to_file","hide_name_regexes",b"hide_name_regexes","max_depth",b"max_depth","min_accelerator_micros",b"min_accelerator_micros","min_bytes",b"min_bytes","min_cpu_micros",b"min_cpu_micros","min_float_ops",b"min_float_ops","min_micros",b"min_micros","min_occurrence",b"min_occurrence","min_output_bytes",b"min_output_bytes","min_params",b"min_params","min_peak_bytes",b"min_peak_bytes","min_residual_bytes",b"min_residual_bytes","order_by",b"order_by","output",b"output","select",b"select","show_name_regexes",b"show_name_regexes","start_name_regexes",b"start_name_regexes","step",b"step","trim_name_regexes",b"trim_name_regexes"]) -> None: ...
global___OptionsProto = OptionsProto

class AdvisorOptionsProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class CheckersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> global___AdvisorOptionsProto.CheckerOption: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[global___AdvisorOptionsProto.CheckerOption] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    class CheckerOption(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        class OptionsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor
            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: typing.Text
            value: typing.Text
            def __init__(self,
                *,
                key: typing.Text = ...,
                value: typing.Text = ...,
                ) -> None: ...
            def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

        OPTIONS_FIELD_NUMBER: builtins.int
        @property
        def options(self) -> google.protobuf.internal.containers.ScalarMap[typing.Text, typing.Text]: ...
        def __init__(self,
            *,
            options: typing.Optional[typing.Mapping[typing.Text, typing.Text]] = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["options",b"options"]) -> None: ...

    CHECKERS_FIELD_NUMBER: builtins.int
    @property
    def checkers(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___AdvisorOptionsProto.CheckerOption]:
        """checker name -> a dict of key-value options."""
        pass
    def __init__(self,
        *,
        checkers: typing.Optional[typing.Mapping[typing.Text, global___AdvisorOptionsProto.CheckerOption]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["checkers",b"checkers"]) -> None: ...
global___AdvisorOptionsProto = AdvisorOptionsProto
