# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_serving/apis/input.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pythie_serving.tensorflow_proto.tensorflow.core.example import example_pb2 as tensorflow_dot_core_dot_example_dot_example__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#tensorflow_serving/apis/input.proto\x12\x12tensorflow.serving\x1a%tensorflow/core/example/example.proto\"4\n\x0b\x45xampleList\x12%\n\x08\x65xamples\x18\x01 \x03(\x0b\x32\x13.tensorflow.Example\"e\n\x16\x45xampleListWithContext\x12%\n\x08\x65xamples\x18\x01 \x03(\x0b\x32\x13.tensorflow.Example\x12$\n\x07\x63ontext\x18\x02 \x01(\x0b\x32\x13.tensorflow.Example\"\xa1\x01\n\x05Input\x12;\n\x0c\x65xample_list\x18\x01 \x01(\x0b\x32\x1f.tensorflow.serving.ExampleListB\x02(\x01H\x00\x12S\n\x19\x65xample_list_with_context\x18\x02 \x01(\x0b\x32*.tensorflow.serving.ExampleListWithContextB\x02(\x01H\x00\x42\x06\n\x04kindB\x03\xf8\x01\x01\x62\x06proto3')



_EXAMPLELIST = DESCRIPTOR.message_types_by_name['ExampleList']
_EXAMPLELISTWITHCONTEXT = DESCRIPTOR.message_types_by_name['ExampleListWithContext']
_INPUT = DESCRIPTOR.message_types_by_name['Input']
ExampleList = _reflection.GeneratedProtocolMessageType('ExampleList', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLELIST,
  '__module__' : 'tensorflow_serving.apis.input_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.serving.ExampleList)
  })
_sym_db.RegisterMessage(ExampleList)

ExampleListWithContext = _reflection.GeneratedProtocolMessageType('ExampleListWithContext', (_message.Message,), {
  'DESCRIPTOR' : _EXAMPLELISTWITHCONTEXT,
  '__module__' : 'tensorflow_serving.apis.input_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.serving.ExampleListWithContext)
  })
_sym_db.RegisterMessage(ExampleListWithContext)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'tensorflow_serving.apis.input_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.serving.Input)
  })
_sym_db.RegisterMessage(Input)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _INPUT.fields_by_name['example_list']._options = None
  _INPUT.fields_by_name['example_list']._serialized_options = b'(\001'
  _INPUT.fields_by_name['example_list_with_context']._options = None
  _INPUT.fields_by_name['example_list_with_context']._serialized_options = b'(\001'
  _EXAMPLELIST._serialized_start=98
  _EXAMPLELIST._serialized_end=150
  _EXAMPLELISTWITHCONTEXT._serialized_start=152
  _EXAMPLELISTWITHCONTEXT._serialized_end=253
  _INPUT._serialized_start=256
  _INPUT._serialized_end=417
# @@protoc_insertion_point(module_scope)
