# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow_serving/apis/status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pythie_serving.tensorflow_proto.tensorflow.core.protobuf import error_codes_pb2 as tensorflow_dot_core_dot_protobuf_dot_error__codes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$tensorflow_serving/apis/status.proto\x12\x12tensorflow.serving\x1a*tensorflow/core/protobuf/error_codes.proto\"k\n\x0bStatusProto\x12\x36\n\nerror_code\x18\x01 \x01(\x0e\x32\x16.tensorflow.error.CodeR\nerror_code\x12$\n\rerror_message\x18\x02 \x01(\tR\rerror_messageB\x03\xf8\x01\x01\x62\x06proto3')



_STATUSPROTO = DESCRIPTOR.message_types_by_name['StatusProto']
StatusProto = _reflection.GeneratedProtocolMessageType('StatusProto', (_message.Message,), {
  'DESCRIPTOR' : _STATUSPROTO,
  '__module__' : 'tensorflow_serving.apis.status_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.serving.StatusProto)
  })
_sym_db.RegisterMessage(StatusProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\370\001\001'
  _STATUSPROTO._serialized_start=104
  _STATUSPROTO._serialized_end=211
# @@protoc_insertion_point(module_scope)
