"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2020 The TensorFlow Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import tensorflow.compiler.tf2xla.host_compute_metadata_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GetTpuProgramResponseExternal(google.protobuf.message.Message):
    """Response for GetTpuProgram RPC."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class Blob(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DATA_FIELD_NUMBER: builtins.int
        data: builtins.bytes
        def __init__(
            self,
            *,
            data: builtins.bytes = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["data", b"data"]) -> None: ...

    PROTO_FIELD_NUMBER: builtins.int
    HOST_COMPUTE_METADATA_FIELD_NUMBER: builtins.int
    MAY_MODIFY_VARIABLES_FIELD_NUMBER: builtins.int
    COMPILER_METADATA_FIELD_NUMBER: builtins.int
    IS_EMPTY_FIELD_NUMBER: builtins.int
    @property
    def proto(self) -> global___GetTpuProgramResponseExternal.Blob: ...
    @property
    def host_compute_metadata(self) -> tensorflow.compiler.tf2xla.host_compute_metadata_pb2.HostComputeMetadata: ...
    may_modify_variables: builtins.bool
    @property
    def compiler_metadata(self) -> global___GetTpuProgramResponseExternal.Blob: ...
    is_empty: builtins.bool
    """Whether the program is empty, which could be true for sharding/unsharding
    entries.
    """
    def __init__(
        self,
        *,
        proto: global___GetTpuProgramResponseExternal.Blob | None = ...,
        host_compute_metadata: tensorflow.compiler.tf2xla.host_compute_metadata_pb2.HostComputeMetadata | None = ...,
        may_modify_variables: builtins.bool = ...,
        compiler_metadata: global___GetTpuProgramResponseExternal.Blob | None = ...,
        is_empty: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["compiler_metadata", b"compiler_metadata", "host_compute_metadata", b"host_compute_metadata", "proto", b"proto"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["compiler_metadata", b"compiler_metadata", "host_compute_metadata", b"host_compute_metadata", "is_empty", b"is_empty", "may_modify_variables", b"may_modify_variables", "proto", b"proto"]) -> None: ...

global___GetTpuProgramResponseExternal = GetTpuProgramResponseExternal
