# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorflow/core/tpu/kernels/tpu_compilation_cache.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pythie_serving.tensorflow_proto.tensorflow.compiler.tf2xla import host_compute_metadata_pb2 as tensorflow_dot_compiler_dot_tf2xla_dot_host__compute__metadata__pb2
from pythie_serving.tensorflow_proto.tensorflow.core.tpu.kernels import tpu_compilation_cache_common_pb2 as tensorflow_dot_core_dot_tpu_dot_kernels_dot_tpu__compilation__cache__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7tensorflow/core/tpu/kernels/tpu_compilation_cache.proto\x12\x0etensorflow.tpu\x1a\x36tensorflow/compiler/tf2xla/host_compute_metadata.proto\x1a>tensorflow/core/tpu/kernels/tpu_compilation_cache_common.proto\"\xbe\x02\n\x1dGetTpuProgramResponseExternal\x12\x41\n\x05proto\x18\x01 \x01(\x0b\x32\x32.tensorflow.tpu.GetTpuProgramResponseExternal.Blob\x12\x45\n\x15host_compute_metadata\x18\x02 \x01(\x0b\x32&.tensorflow.tf2xla.HostComputeMetadata\x12\x1c\n\x14may_modify_variables\x18\x03 \x01(\x08\x12M\n\x11\x63ompiler_metadata\x18\x04 \x01(\x0b\x32\x32.tensorflow.tpu.GetTpuProgramResponseExternal.Blob\x12\x10\n\x08is_empty\x18\x05 \x01(\x08\x1a\x14\n\x04\x42lob\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x8c\x01\n\"TpuCompilationCacheServiceExternal\x12\x66\n\rGetTpuProgram\x12$.tensorflow.tpu.GetTpuProgramRequest\x1a-.tensorflow.tpu.GetTpuProgramResponseExternal\"\x00\x62\x06proto3')



_GETTPUPROGRAMRESPONSEEXTERNAL = DESCRIPTOR.message_types_by_name['GetTpuProgramResponseExternal']
_GETTPUPROGRAMRESPONSEEXTERNAL_BLOB = _GETTPUPROGRAMRESPONSEEXTERNAL.nested_types_by_name['Blob']
GetTpuProgramResponseExternal = _reflection.GeneratedProtocolMessageType('GetTpuProgramResponseExternal', (_message.Message,), {

  'Blob' : _reflection.GeneratedProtocolMessageType('Blob', (_message.Message,), {
    'DESCRIPTOR' : _GETTPUPROGRAMRESPONSEEXTERNAL_BLOB,
    '__module__' : 'tensorflow.core.tpu.kernels.tpu_compilation_cache_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.tpu.GetTpuProgramResponseExternal.Blob)
    })
  ,
  'DESCRIPTOR' : _GETTPUPROGRAMRESPONSEEXTERNAL,
  '__module__' : 'tensorflow.core.tpu.kernels.tpu_compilation_cache_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.tpu.GetTpuProgramResponseExternal)
  })
_sym_db.RegisterMessage(GetTpuProgramResponseExternal)
_sym_db.RegisterMessage(GetTpuProgramResponseExternal.Blob)

_TPUCOMPILATIONCACHESERVICEEXTERNAL = DESCRIPTOR.services_by_name['TpuCompilationCacheServiceExternal']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTPUPROGRAMRESPONSEEXTERNAL._serialized_start=196
  _GETTPUPROGRAMRESPONSEEXTERNAL._serialized_end=514
  _GETTPUPROGRAMRESPONSEEXTERNAL_BLOB._serialized_start=494
  _GETTPUPROGRAMRESPONSEEXTERNAL_BLOB._serialized_end=514
  _TPUCOMPILATIONCACHESERVICEEXTERNAL._serialized_start=517
  _TPUCOMPILATIONCACHESERVICEEXTERNAL._serialized_end=657
# @@protoc_insertion_point(module_scope)
